### ISSUE TITLE
Responder Not Found

### ISSUE THREAD

**Issue by ranjithprethan** [deepzec/Bad-Pdf#11]
Hi,

when i try to execute the command from the kali terminal ( python bad.pdf.py), i get the error message" Responder not found"  I have responder program installed in my usr/bin folder. Any help? much appreciated. Thanks

**Comment by deepzec** [comment]
Bad-pdf check for presence of responder executable in /usr/bin and it will ask you to enter full alternative path if it's not able to find it there.

**Comment by deepzec** [comment]
Also try responder path /usr/sbin/responder  they changed responder path to /usr/sbin in new version
