### ISSUE TITLE
command not found 

### ISSUE THREAD

**Issue by mav51** [deepzec/Bad-Pdf#13]
Hey there,
I get this result when i run the script:
[*] Starting Process.. [*]
Bad PDF test.pdf created
/usr/bin/responder: line 2: d: command not found

**Comment by deepzec** [comment]
Bad-pdf check for presence of responder executable in /usr/bin and it will ask you to enter full alternative path if it's not able to find it there, try responder path /usr/sbin/responder Kali linux changed responder path to /usr/sbin in new version.
