### ISSUE TITLE
Responder Not Found

### ISSUE THREAD

**Issue by DizKiller** [deepzec/Bad-Pdf#2]
"Responder not found..
Please enter responder path (Default /usr/bin/responder): "

That is what i get when i run 'python badpdf.py' as root.
I have googled, and read the 'Readme'
I am not sure what to do. Please help. Thank you

**Comment by devil67** [comment]
Hello DizKiller here the solution

open mousepad or leafpad and put this code
________________________________________

#!/bin/bash

cd /usr/share/Responder/ && ./Responder.py "$@"
------------------------------------------------------------------

save as responder 
________________________________________
Open terminal:

sudo mv responder /usr/bin/     press enter

sudo chmod +x /usr/bin/responder    press enter

sudo cd /usr/share/     press enter

sudo git clone https://github.com/SpiderLabs/Responder.git  press enter

sudo chmod 777 /usr/share/Responder/    press enter
__________________________________________
Finish:
try now comand
sudo python badpdf.py  :+1:

**Comment by deepzec** [comment]
Hi DizKiller

Bad-pdf require responder to work. You can follow steps mentioned by devil67 or use kali linux

**Comment by mav51** [comment]
Hi,
I am getting this error after running the script:
[*] Starting Process.. [*]
Bad PDF test.pdf created
/usr/bin/responder: line 2: d: command not found
any ideas!!!
