### ISSUE TITLE
http responder server support

### ISSUE THREAD

**Issue by thesle3p** [deepzec/Bad-Pdf#5]
Blocking port 445 on a gateway is considered a best practice which makes using responder's smb service less reliable. Luckily you can get the same results by using responder's http service and specifying the listener with http:/// as the /AA entry. Would it be possible to add support for this to Bad-PDF?

**Comment by deepzec** [comment]
Hi thesle3p,

Thanks for the input, I have added support to send NTLM hashes over HTTP. Please check the latest version
