### ISSUE TITLE
responder issue

### ISSUE THREAD

**Issue by y0d4a** [deepzec/Bad-Pdf#9]
Hi, after creating file, i got:
/bin/sh: 1: -I: not found

it`s on latest kali ver.

**Comment by ExcitedPirate** [comment]
I just discovered the same issue as well. Kali appears to have moved its binaries to /usr/share/responder instead of /usr/bin/responder that this script is looking for.
I get errors even when specifying the valid path.

**Comment by y0d4a** [comment]
no, responder is in sbin, that is fine for me. But flags which is used seems are wrong..

**Comment by y0d4a** [comment]
# python badpdf.py


        ______                 __       _______  ______   ________
        |_   _ \               |  ]     |_   __ \|_   _ `.|_   __  |
          | |_) |  ,--.    .--.| | ______ | |__) | | | `. \ | |_ \_|
          |  __'. `'_\ : / /'`' ||______||  ___/  | |  | | |  _|
         _| |__) |// | |,| \__/  |       _| |_    _| |_.' /_| |_
        |_______/ '-;__/ '.__.;__]     |_____|  |______.'|_____|

        By DeepZec

        =============================================================

Responder not found..
Please enter responder path (Default /usr/sbin/responder):

Please enter Bad-PDF host IP:
1.1.1.1
Please enter output file name:
test.pdf
Please enter the interface name to listen(Default eth0):

[*] Starting Process.. [*]
Bad PDF test.pdf created
/bin/sh: 1: -I: not found

**Comment by y0d4a** [comment]
1. you need to enter all what he request from you, do not leave blank\
2. responder now is in: /usr/sbin/responder

now is working for me

**Comment by jaikishantulswani** [comment]
Error: -wF: Interface not found
even the interface is eth0

**Comment by deepzec** [comment]
@y0d4a Glad to see you resolve the issue
@jaikishantulswani did you provide eth0 while configuring Bad-PDF?
